services:
  - type: web
    name: yt-transcriber
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn "yt_transcriber:create_app()"
